### ISSUE TITLE
Too much text on one intro screen

### ISSUE THREAD

**Issue by thunderrabbit** [Nagshell/elemental-inception-incremental#5]
One time, the exposition text overflows the box.

![screen shot 2018-06-21 at 11 12 24 pm](https://user-images.githubusercontent.com/21597/41724539-bb797a2a-75a8-11e8-8575-e6f8e96f88d9.png)

**Comment by Nagshell** [comment]
Hm, I'm almost sure it wasn't on my end.

Well, fixing it will be quite easy, as all messages are located in new Messages.js file.

I even included tutorial message that's not used in game to explain which parts have what meaning. 

From now on any pull requests are very appreciated. I'd love to focus on planning stage 2 today.

**Comment by thunderrabbit** [comment]
> focus on planning stage 2 today.

Sounds good!

I am just going to post this here as well in case someone wants to look at these.  They are essentially the same issue.

![screen shot 2018-06-21 at 11 56 09 pm](https://user-images.githubusercontent.com/21597/41727311-ffdc9de0-75ae-11e8-9dbe-642358767744.png)
